##  Random Number Generation


1. Random Number Generation

In [60]:
import numpy as np

In [62]:
# Uniform distribution
uniform = np.random.rand(3, 3)
print("🎯 Uniform distribution:\n", uniform)

🎯 Uniform distribution:
 [[0.13997903 0.57987641 0.55166097]
 [0.32965668 0.28682374 0.96392065]
 [0.48001587 0.50712895 0.50234988]]


In [64]:
# Normal distribution
normal = np.random.randn(3, 3)
print("\n📈 Normal distribution:\n", normal)


📈 Normal distribution:
 [[-1.78848679  2.01054097 -0.10297325]
 [-0.68467578 -0.9181973   1.89819714]
 [-0.24106423  1.64396531 -0.38916886]]



###  Searching in Arrays

In [67]:
arr = np.array([1, 2, 3, 4, 5])

In [69]:
np.where(arr > 3)

(array([3, 4], dtype=int64),)

In [71]:
np.where(arr<=2)

(array([0, 1], dtype=int64),)

In [73]:
np.where(arr>5)

(array([], dtype=int64),)

In [75]:
print("Where > 3:", np.where(arr > 3))

Where > 3: (array([3, 4], dtype=int64),)


In [77]:
arr = np.array([1, 2, 3, 4, 5])

In [79]:
np.argmax(arr)

4

In [81]:
np.argmin(arr)

0

In [83]:
print("Max Index:", np.argmax(arr))

Max Index: 4


In [85]:
print("Min Index:", np.argmin(arr))

Min Index: 0


In [87]:
sorted_arr = np.array([1, 3, 5 , 7 ])

In [89]:
np.searchsorted(sorted_arr, 6)

3

In [91]:
np.searchsorted(sorted_arr, 100)

4

In [93]:
np.searchsorted(sorted_arr, 0)

0

In [95]:

print("Insert 6 at index:", np.searchsorted(sorted_arr, 6))

Insert 6 at index: 3


In [97]:
arr = np.array([1, 2, 3, 4, 5])

In [99]:
print("Extract > 3:", np.extract(arr > 3, arr))

Extract > 3: [4 5]



###  Transposing Arrays

Transposing means flipping an array’s rows and columns.  
This is essential for matrix operations and organizing data.

In [10]:
import numpy as np
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Original:\n", matrix)
print("Transposed:\n", np.transpose(matrix))


Original:
 [[1 2 3]
 [4 5 6]]
Transposed:
 [[1 4]
 [2 5]
 [3 6]]


In [14]:
# mean calculation
arr = np.array([1, 2, 3, 4, 5])


In [16]:
print("Mean value:", np.mean(arr))

Mean value: 3.0


## splitting arrays

In [19]:
# into equal parts
arr = np.array([1,  2, 3, 4, 5, 6])



np.split(arr, 3)

[array([1, 2]), array([3, 4]), array([5, 6])]

In [21]:
# Split at specific positions
np.split(arr, [1, 4])

[array([1]), array([2, 3, 4]), array([5, 6])]

In [23]:
print("Split at Indices:", ) # Split at specific positions 

Split at Indices:


In [27]:
matrix = np.array([[1,| 2,| 3], 
                 
                   [4,| 5,| 6]])

SyntaxError: invalid syntax (337996270.py, line 1)

In [29]:
np.split(matrix, 3, axis=1)   #→ Split columns

[array([[1],
        [4]]),
 array([[2],
        [5]]),
 array([[3],
        [6]])]

In [31]:
[[1, 2, 3],
 [4, 5, 6]]

[[1, 2, 3], [4, 5, 6]]

In [33]:
[ [ [1], [4] ],
 
  [ [2], [5] ],
 
  [ [3], [6] ] ]


[[[1], [4]], [[2], [5]], [[3], [6]]]

In [35]:
np.split(matrix, 2, axis=0) 

[array([[1, 2, 3]]), array([[4, 5, 6]])]

In [37]:
Original Matrix:
[ [1, 2, 3],
  [4, 5, 6] ]

Split along axis=0 (rows):
→   [1, 2, 3]
     ↓
     [4, 5, 6]

Result:
[
 [[1, 2, 3]],
 [[4, 5, 6]]
]


SyntaxError: invalid character '→' (U+2192) (588533033.py, line 6)

In [39]:
# sorting arrays

arr = np.array([3, 1, 4, 2])


In [41]:
print("Sorted Copy:", np.sort(arr))

Sorted Copy: [1 2 3 4]


In [43]:
arr

array([3, 1, 4, 2])

In [45]:
arr.sort()

In [47]:
arr

array([1, 2, 3, 4])

In [49]:
matrix = np.array([[3, 1, 2],
                   [6, 5, 4]])

In [51]:

print("Sorted Rows:\n", np.sort(matrix, axis=1))

Sorted Rows:
 [[1 2 3]
 [4 5 6]]


In [55]:
print("Sorted columns:\n", np.sort(matrix, axis=0))

Sorted columns:
 [[3 1 2]
 [6 5 4]]


## joining arrays

vertical join 

In [60]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])

In [62]:
print("Vertical Join:\n", np.concatenate((arr1, arr2), axis=0))

Vertical Join:
 [[1 2]
 [3 4]
 [5 6]]


horizontal

In [65]:
a = np.array([1, 2])
b = np.array([3, 4])

In [67]:
print("Horizontal Join:\n", np.hstack((a, b)))

Horizontal Join:
 [1 2 3 4]


In [69]:
arr3 = np.array([1, 2, 3])
arr4 = np.array([4, 5, 6])

In [71]:
print("Vertical Stack:\n", np.vstack((arr3, arr4)))

Vertical Stack:
 [[1 2 3]
 [4 5 6]]


In [73]:
### Stacks arrays vertically (row-wise)### Stacks arrays vertically (row-wise)

## filtering arrays

In [76]:
arr = np.array([1, 2, 3, 4, 5, 6])

In [78]:
# Filter values > 3
print("Filtered > 3:", arr[arr > 3])

Filtered > 3: [4 5 6]


In [80]:
# Filter values between 2 and 6
print("Between 2 and 6:", arr[(arr > 2) & (arr < 6)])

Between 2 and 6: [3 4 5]
