### What is Numpy?

NumPy is a powerful Python library for numerical and scientific computations. It provides support for large, multi-dimensional arrays and matrices, along with a wide range of mathematical functions to operate on these arrays. NumPy is the foundation for many data science and scientific computing libraries in Python. Here are some basic concepts of NumPy:



In [2]:
my_list = [1, 2, 3, 4, 5]

In [4]:
my_list + 2

TypeError: can only concatenate list (not "int") to list

In [6]:
l = [1,2,3,45]

In [10]:
l

[1, 2, 3, 45]

In [12]:
from array import array
my_array = array('i', [1, 2, 3, 4, 5])

In [14]:
l = [1,1,2,3]

In [16]:
l

[1, 1, 2, 3]

In [18]:
import numpy as np

In [20]:
arr = np.array([1,2,3,4])

In [22]:
arr

array([1, 2, 3, 4])

In [24]:
type(arr)

numpy.ndarray

In [26]:
arr.ndim

1

In [28]:
arr.dtype

dtype('int32')

In [30]:
import numpy as np

In [32]:
array_new = np.array([1,2,3,4,5,6])

In [34]:
array_new + 3

array([4, 5, 6, 7, 8, 9])

In [36]:
type(array_new)

numpy.ndarray

In [38]:
import numpy as np

my_numpy_array = np.array([1, 2, 3, 4, 5])

In [40]:
import numpy as np

my_numpy_array = np.array([1, 2, 3, 4, 5])

In [42]:
new_arr=my_numpy_array*3

In [44]:
new_arr


array([ 3,  6,  9, 12, 15])

In [46]:
type(my_numpy_array)

numpy.ndarray

In [48]:
l

[1, 1, 2, 3]

In [50]:
l*3

[1, 1, 2, 3, 1, 1, 2, 3, 1, 1, 2, 3]

In [52]:
l *3

[1, 1, 2, 3, 1, 1, 2, 3, 1, 1, 2, 3]

In [54]:
array_new

array([1, 2, 3, 4, 5, 6])

In [56]:
array_new * 2

array([ 2,  4,  6,  8, 10, 12])

In [58]:
import numpy as np

my_array = np.array([1, 2, 3])
result = my_array * 2
print(result)

[2 4 6]


In [60]:
arr

array([1, 2, 3, 4])

In [62]:
arr>2

array([False, False,  True,  True])

In [64]:
import seaborn as sns

In [66]:
df = sns.load_dataset("titanic")

URLError: <urlopen error [Errno 11001] getaddrinfo failed>

In [68]:
df.head()

NameError: name 'df' is not defined