### What is Numpy?

NumPy is a powerful Python library for numerical and scientific computations. It provides support for large, multi-dimensional arrays and matrices, along with a wide range of mathematical functions to operate on these arrays. NumPy is the foundation for many data science and scientific computing libraries in Python. Here are some basic concepts of NumPy:



In [2]:
my_list = [1, 2, 3, 4, 5]

In [4]:
my_list + 2

TypeError: can only concatenate list (not "int") to list

In [6]:
l = [1,2,3,45]

In [10]:
l

[1, 2, 3, 45]

In [12]:
from array import array
my_array = array('i', [1, 2, 3, 4, 5])

In [14]:
l = [1,1,2,3]

In [16]:
l

[1, 1, 2, 3]

In [18]:
import numpy as np

In [20]:
arr = np.array([1,2,3,4])

In [22]:
arr

array([1, 2, 3, 4])

In [24]:
type(arr)

numpy.ndarray

In [26]:
arr.ndim

1

In [28]:
arr.dtype

dtype('int32')

In [30]:
import numpy as np

In [32]:
array_new = np.array([1,2,3,4,5,6])

In [34]:
array_new + 3

array([4, 5, 6, 7, 8, 9])

In [36]:
type(array_new)

numpy.ndarray

In [38]:
import numpy as np

my_numpy_array = np.array([1, 2, 3, 4, 5])

In [40]:
import numpy as np

my_numpy_array = np.array([1, 2, 3, 4, 5])

In [42]:
new_arr=my_numpy_array*3

In [44]:
new_arr


array([ 3,  6,  9, 12, 15])

In [46]:
type(my_numpy_array)

numpy.ndarray

In [48]:
l

[1, 1, 2, 3]

In [50]:
l*3

[1, 1, 2, 3, 1, 1, 2, 3, 1, 1, 2, 3]

In [52]:
l *3

[1, 1, 2, 3, 1, 1, 2, 3, 1, 1, 2, 3]

In [54]:
array_new

array([1, 2, 3, 4, 5, 6])

In [56]:
array_new * 2

array([ 2,  4,  6,  8, 10, 12])

In [58]:
import numpy as np

my_array = np.array([1, 2, 3])
result = my_array * 2
print(result)

[2 4 6]


In [60]:
arr

array([1, 2, 3, 4])

In [62]:
arr>2

array([False, False,  True,  True])

In [9]:
array_2d = np.array([[1,2,3],[4,5,6]])
array_2d

NameError: name 'np' is not defined

In [7]:
array_2d.shape

NameError: name 'array_2d' is not defined

In [5]:
array_2d.ndim

NameError: name 'array_2d' is not defined

In [3]:
array_2d

NameError: name 'array_2d' is not defined

In [1]:
array_2d * 10 

NameError: name 'array_2d' is not defined

In [11]:
   import numpy as np

   list_data = [1, 2, 3, 4, 5]
   array_from_list = np.array(list_data)

In [13]:
list_data

[1, 2, 3, 4, 5]

In [15]:
type(list_data)

list

In [17]:
list_data

[1, 2, 3, 4, 5]

In [19]:
array_from_list

array([1, 2, 3, 4, 5])

In [21]:
type(array_from_list)

numpy.ndarray

In [23]:
array_from_list.dtype

dtype('int32')

In [25]:
lis1 = [1,2,3,4,5]

In [27]:
lis1

[1, 2, 3, 4, 5]

In [37]:
df

NameError: name 'df' is not defined

In [39]:
arr = np.array([4,5,6,8,9,8,5])

In [41]:
arr

array([4, 5, 6, 8, 9, 8, 5])

In [43]:
arr+10

array([14, 15, 16, 18, 19, 18, 15])

In [45]:
   tuple_data = (5.5, 6.6, 7.7)
   array_from_tuple = np.array(tuple_data)

In [47]:
list_data = [1, 2, 3, 4, 5]


In [49]:
a11 = np.array(list_data)

In [51]:
a11


array([1, 2, 3, 4, 5])

In [53]:
tuple_data = (5.5, 6.6, 7.7)
a22 = np.array(tuple_data)

In [55]:
a22

array([5.5, 6.6, 7.7])

2. **Using Functions to Generate Data

In [58]:
a33 = np.ones((3,4))

In [60]:
type(a33)

numpy.ndarray

In [62]:
a33

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [64]:
a44 = np.zeros((2,4))

In [66]:
a44

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [68]:
import numpy as np

array1 = np.array([1,2,3])

In [70]:
   import numpy as np

   zeros_array = np.zeros((3, 3))   

In [72]:
    ones_array = np.ones((2, 4)) 

In [76]:
   identity_matrix = np.eye(3) 

In [78]:
identity_matrix


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [80]:
   random_array = np.random.rand(4, 4) 

Specifying Data Type

In [83]:
l = [1,2,3,4]

In [85]:
np.array(l,dtype=np.int32 )

array([1, 2, 3, 4])

In [87]:
   import numpy as np

   int_array = np.array([1, 2, 3], dtype=np.int32)
   float_array = np.array([0.1, 0.2, 0.3], dtype=np.float64)

Using arange and linspac

In [90]:
a44 = np.arange(0,12)

In [92]:
a66=np.arange(5,7)

In [94]:
a66

array([5, 6])

In [96]:
a44


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [98]:
   import numpy as np

   range_array = np.arange(0, 10, 2)      # Array from 0 to 10 (exclusive) with step 2
   linspace_array = np.linspace(0, 10, 5) 

In [100]:
linspace_array


array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [102]:
linspace_array_2 = np.linspace(0, 10, 6)
linspace_array_2


array([ 0.,  2.,  4.,  6.,  8., 10.])

In [104]:
linspace_array_3=np.linspace(0,15,4)

In [106]:
linspace_array_3

array([ 0.,  5., 10., 15.])

In [108]:
list_data = [1, 2, 3, 4, 5]
array_from_list = np.array(list_data)

In [110]:
array_from_list


array([1, 2, 3, 4, 5])

In [112]:
tuple_data = (5.5, 6.6, 7.7)
array_from_tuple = np.array(tuple_data)

In [114]:
zeros_array = np.zeros((3, 3))      
ones_array = np.ones((2, 4))       
identity_matrix = np.eye(3)        

random_array = np.random.rand(4, 4)

In [116]:
random_array

array([[0.35652883, 0.98049281, 0.0928021 , 0.80292585],
       [0.89562866, 0.70878801, 0.65456118, 0.85912429],
       [0.87823362, 0.75712256, 0.12786549, 0.52088369],
       [0.92825876, 0.21471269, 0.01502784, 0.78047377]])

In [118]:
zeros_array


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [120]:
ones_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [122]:
import numpy as np

a1 = np.array([1,2,3,4,5])
print(a1)

[1 2 3 4 5]


In [124]:
# 2D and 3D
b1 = np.array([[1,2,3,5],[4,5,6,8]])
print(b1)

[[1 2 3 5]
 [4 5 6 8]]


In [126]:
[[[],[],[]]]

[[[], [], []]]

In [128]:
a55 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

a55

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [130]:
a55.ndim

3

In [132]:
c1 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c1)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [134]:
# dtype
np.array([10,20,30,40],dtype=float)

array([10., 20., 30., 40.])

In [136]:

np.arange(0,11)   

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [138]:
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [140]:
np.arange(16).reshape(8,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [142]:
(1,2)
(3,2,1)

(3, 2, 1)

In [144]:
# with reshape
np.arange(27).reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [146]:
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [148]:
# np.ones and np.zeros
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [150]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [152]:
np.random.random((3,4))

array([[0.35903124, 0.95322491, 0.57023856, 0.3260548 ],
       [0.34351078, 0.10766624, 0.38668959, 0.10862475],
       [0.45285635, 0.36283932, 0.53810575, 0.9273531 ]])

In [154]:
# np.random
np.random.random((3,5))

array([[0.39975917, 0.32361764, 0.79115523, 0.59669517, 0.7296108 ],
       [0.91866235, 0.88802422, 0.18715365, 0.80934763, 0.0628161 ],
       [0.2157651 , 0.93234019, 0.02671904, 0.54009723, 0.11212685]])

In [156]:
# np.linspace 

np.linspace(-20,20,20,dtype=int)

array([-20, -18, -16, -14, -12, -10,  -8,  -6,  -4,  -2,   1,   3,   5,
         7,   9,  11,  13,  15,  17,  20])

In [158]:
# np.identity
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [160]:
1

1

In [162]:
l.append(5)

In [164]:
1

1

In [174]:
1==([1,2,3,4,5])

False

 NumPy Array Indexing

In [177]:
[1, 2, 3],
[4, 5, 6]
[4, 5, 6]

[4, 5, 6]

2D Example
Slicing
Slicing allows extracting parts of arrays using `[start:stop:step]
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4])    

2D Example
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print(matrix[0:2, 1:3])

Integer Array Indexing
You can pass a list/array of indices to select specific elements


### NumPy Array Slicing

 1D Array Slicing

In [195]:
print(arr[1:4])

[5 6 8]


In [197]:
print(arr[:3])

[4 5 6]


In [199]:
print(arr[::2])

[4 6 9 5]


In [201]:
print(arr[::-1])

[5 8 9 8 6 5 4]


In [203]:
print(matrix[2:3,1:2])

NameError: name 'matrix' is not defined

### 2D Array Slicing

In [206]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [208]:

print(matrix[2:3,1:2])

[[8]]


In [210]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print(matrix[0:2, 1:3]) 

[[2 3]
 [5 6]]


### NumPy Array Copy vs View

In [213]:
a = np.array([1, 2, 3, 4])

In [215]:
b = a[1:3]

In [217]:
b

array([2, 3])

In [219]:
b[0] = 99

In [221]:
b

array([99,  3])

In [223]:
a

array([ 1, 99,  3,  4])

In [225]:
a = np.array([1, 2, 3, 4])

In [227]:
b = a[1:3].copy() 

In [229]:
b[0] = 99

In [231]:
print(a)

[1 2 3 4]


In [233]:
print(b) 

[99  3]


### NumPy Array Shape and Reshaping

In [237]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])

In [240]:
arr.shape

(2, 3)

In [242]:
arr2 = np.array([[1, 2, 3], 
                 [4, 5, 6],
                 [4, 5, 6]])

In [244]:
arr2.shape

(3, 3)

###  Reshaping Arrays

In [247]:
a = np.arange(12)

In [249]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [251]:
b = a.reshape(3, 4)

In [253]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [255]:
c = a.reshape(12, 1)

In [257]:
c

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [261]:
12 

3*4 ===12
6*2====12
12*1===12


3*5==15   \\\\\

SyntaxError: invalid syntax (1962180561.py, line 3)

### Array Attributes

In [266]:
import numpy as np

In [268]:
arr_1d = np.array([1,2,3,4,5,6])

In [270]:
arr_2d = np.array([[1,2,3,4,5,6],
                   [10,20,30,40,50,60]])

In [272]:
arr_2d.transpose()

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30],
       [ 4, 40],
       [ 5, 50],
       [ 6, 60]])

In [274]:
arr_3d=np.array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [276]:
arr_3d.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [278]:
arr_1d.shape

(6,)

In [280]:
arr_2d.shape

(2, 6)

In [282]:
arr.shape

(2, 3)

In [284]:
arr.ndim

2

In [286]:
arr_2d = np.arange(12).reshape(4,3)

In [288]:
arr_2d

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [290]:
df


NameError: name 'df' is not defined

In [292]:
arr_2d.ndim

2

In [294]:
arr_2d.shape

(4, 3)

In [296]:
arr_2d.size

12

### 1. **`ndim`** (Number of Dimensions)

In [299]:
a11 = np.arange(12)
a22 = np.arange(12).reshape(3,4)
a33 = np.arange(27).reshape(3,3,3)

In [301]:
a11

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [303]:
a22

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [305]:
a33

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [307]:
a11.ndim

1

In [309]:
a22.ndim

2

In [311]:
a33.ndim

3

In [313]:
import numpy as np

# 1D Array
array_1d = np.array([1, 2, 3])
array_1d.ndim 

1

In [315]:
array_2d = np.array([[1, 2], [3, 4]])
array_2d.ndim

2


### 2. **`shape`** (Shape of the Array)

In [318]:
a11.shape

(12,)

In [320]:
a11

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [322]:
a22.shape

(3, 4)

In [324]:
a22


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [326]:
a33.shape

(3, 3, 3)

In [328]:
a33


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [330]:
array_1d.shape

(3,)

In [332]:
array_2d.shape

(2, 2)

### 3. **`size`** (Total Number of Elements)

In [335]:
a11.size

12

In [337]:
a22.size

12

In [339]:
a22.shape

(3, 4)

In [341]:
a33.shape

(3, 3, 3)

In [343]:
array_1d.size

3

In [345]:
array_2d.size 

4

### 4. **`dtype`** (Data Type of Elements)Returns the data type of the elements stored in the array.

In [348]:
a11.dtype

dtype('int32')

In [350]:
a22.dtype

dtype('int32')

In [352]:
a33.dtype

dtype('int32')

In [354]:
a33.dtype

dtype('int32')

In [356]:
array_1d.dtype

dtype('int32')

In [358]:
array_2d.dtype

dtype('int32')

### 5. **`itemsize`** (Size of Each Element in Bytes)

In [363]:
a11.itemsize

4

In [365]:
array_1d.itemsize

4

In [367]:

array_2d.itemsize 

4

In [369]:
import numpy as np 

In [371]:
a11 = np.arange(12).reshape(3,4)
a11

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [373]:
a22

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [375]:
a22

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [377]:
a33.ndim

3

In [379]:
a11.ndim

2

In [381]:
print(a33.shape)

(3, 3, 3)


In [383]:
a11.shape

(3, 4)

In [385]:
print(a22.size)
a22

12


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [387]:
a33

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [389]:
# dtype
print(a11.dtype)
print(a22.dtype)
print(a33.dtype)

int32
int32
int32


### Array Operations

### 1. **Addition**
- You can add two arrays element-wise.

In [397]:
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])

In [399]:
a1

array([1, 2, 3])

In [401]:
a2

array([4, 5, 6])

In [403]:
a1+a2

array([5, 7, 9])

In [405]:
a11 = np.array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [407]:
a22 = np.array(([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]))

In [409]:
a11+a22

ValueError: operands could not be broadcast together with shapes (12,) (3,4) 

In [411]:
import numpy as np

# Arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

In [413]:

result_add = array1 + array2
result_add  # Output: array([5, 7, 9])

array([5, 7, 9])


### 2. **Subtraction**

In [416]:
a2 - a1

array([3, 3, 3])

In [418]:
a1

array([1, 2, 3])

In [420]:
a2

array([4, 5, 6])

In [422]:

result_sub = array1 - array2
result_sub  

array([-3, -3, -3])


### 3. **Multiplication**

In [425]:
a1

array([1, 2, 3])

In [427]:
a2

array([4, 5, 6])

In [429]:
a1 *a2

array([ 4, 10, 18])

In [431]:
a1

array([1, 2, 3])

In [433]:
a2

array([4, 5, 6])

In [435]:
result_mul = array1 * array2
result_mul

array([ 4, 10, 18])


### 4. **Division**

In [438]:
a1 /a2

array([0.25, 0.4 , 0.5 ])

In [440]:
a1[0] = 15

In [443]:
result_div = array1 / array2
result_div 

array([0.25, 0.4 , 0.5 ])


### 5. **Scalar Operations**

In [448]:
a1 +10

array([25, 12, 13])

In [450]:
a1*25

array([375,  50,  75])

In [452]:
a1 - 3

array([12, -1,  0])

In [454]:
a22 *33

array([[  0,  33,  66,  99],
       [132, 165, 198, 231],
       [264, 297, 330, 363]])

In [456]:
a33 + 10

array([[[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]],

       [[28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]]])

In [458]:
result_scalar_add = array1 + 10
result_scalar_add 

array([11, 12, 13])

In [460]:
result_scalar_mul = array1 * 2
result_scalar_mul

array([2, 4, 6])

### 6. **Exponentiation**

In [463]:
array1


array([1, 2, 3])

In [465]:
result_pow = array1 ** 2
result_pow

array([1, 4, 9])

### 7. **Modulus**

In [470]:
array1

array([1, 2, 3])

In [472]:
a1 %a2

array([3, 2, 3])

In [474]:
result_mod = array1 % 2
result_mod

array([1, 0, 1], dtype=int32)

In [476]:
a = np.array([2,4,6])

In [478]:
a%2

array([0, 0, 0], dtype=int32)

### dot product 

In [483]:
result_dot = np.dot(array1, array2)
result_dot 

32

### 1. **Greater Than (`>`)**

In [488]:
3>2

True

In [490]:
a1

array([15,  2,  3])

In [492]:
a11 > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True])

In [494]:
3>2

True

In [496]:
a21 = np.arange(12).reshape(3,4)

In [498]:
a21


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [500]:
a33 = np.arange(27).reshape(3,3,3)

In [502]:
a11 = np.arange(12)

In [504]:
a11

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [506]:
import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.array([2, 2, 4])

In [508]:
a1

array([15,  2,  3])

In [510]:
a2


array([4, 5, 6])

In [512]:
a1 < a2

array([False,  True,  True])

In [514]:
array1


array([1, 2, 3])

In [516]:
array2


array([2, 2, 4])

In [518]:
result_gt = array1 > array2
result_g

NameError: name 'result_g' is not defined

In [520]:
a11

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [522]:
a11>3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True])

In [524]:
a21>8

array([[False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True]])



### 2. **Less Than (`<`)**

In [529]:
result_lt = array1 < array2
result_lt 

array([ True, False,  True])


### 3. **Greater Than or Equal To (`>=`)**

In [532]:
a11

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [534]:
a21

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [536]:
3>2

True

In [538]:
a21 >= 2

array([[False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [540]:
a33

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [542]:
a22 >= 5

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [544]:
2>3

False

In [546]:
3>3

False

In [548]:
arr


array([[1, 2, 3],
       [4, 5, 6]])

In [550]:
arr>5

array([[False, False, False],
       [False, False,  True]])

In [552]:
arr[arr>5]

array([6])

In [554]:
arr[arr<5]

array([1, 2, 3, 4])

In [556]:
result_ge = array1 >= array2
result_ge

array([False,  True, False])


### 4. **Less Than or Equal To (`<=`)**

In [561]:
result_le = array1 <= array2
result_le 

array([ True,  True,  True])

### 5. **Equal To (`==`)**

In [564]:
a22 == 5

array([[False, False, False, False],
       [False,  True, False, False],
       [False, False, False, False]])

In [566]:
a21 == 8

array([[False, False, False, False],
       [False, False, False, False],
       [ True, False, False, False]])

In [568]:
result_eq = array1 == array2
result_eq 

array([False,  True, False])

In [570]:
l = [1,2,3,45]

In [574]:
1>2

False

In [576]:
a11 != 3

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True])

In [578]:
result_ne = array1 != array2
result_ne

array([ True, False,  True])

### Logical Operations on Numerical Arrays:

In [581]:
a1

array([15,  2,  3])

In [583]:
a2

array([4, 5, 6])

In [585]:
import numpy as np

# Numerical arrays
array1 = np.array([10, 20, 30, 40])

array2 = np.array([15, 20, 25, 50])

In [587]:
array1 > 15

array([False,  True,  True,  True])

In [589]:
array2 < 30

array([ True,  True,  True, False])

In [591]:
True and False 

False

In [593]:
array1 > 15

array([False,  True,  True,  True])

In [595]:
array2 < 30

array([ True,  True,  True, False])

In [597]:
(array1 > 3) and  (array2 > 5)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [599]:
& == and
| == or
~ == not

SyntaxError: invalid syntax (1693014925.py, line 1)

In [601]:
array1

array([10, 20, 30, 40])

In [603]:
array2


array([15, 20, 25, 50])

In [605]:
(array1 > 3) & (array2 > 5)

array([ True,  True,  True,  True])

In [607]:
not True

False

In [609]:
True not False

SyntaxError: invalid syntax (427692260.py, line 1)

In [611]:
~(a1>3)

array([False,  True,  True])

In [613]:
(array1 > 15) & (array2 < 30)         

array([False,  True,  True, False])

In [615]:
a22 = np.arange(12).reshape(3,4)

In [618]:
a22

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [620]:
a22[(a22>2) & (a22<8)]

array([3, 4, 5, 6, 7])

In [622]:
a11


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [624]:
and &

SyntaxError: invalid syntax (1320882720.py, line 1)

In [626]:
(a11 >3) & (a11<10)

array([False, False, False, False,  True,  True,  True,  True,  True,
        True, False, False])

In [628]:
result_and = (array1 > 15) & (array2 < 30)
result_and 

array([False,  True,  True, False])

In [630]:
(array1 > 15)

array([False,  True,  True,  True])

In [632]:
(array2 < 30)

array([ True,  True,  True, False])

In [634]:
(array1 > 15) | (array2 < 30)

array([ True,  True,  True,  True])

In [636]:
a21

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [638]:
(a21> 10) | (a21>30)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True]])

In [640]:
result_or = (array1 > 15) | (array2 < 30)
result_or 

array([ True,  True,  True,  True])

In [642]:
result_not = ~(array1 > 15)
result_not 

array([ True, False, False, False])