### Array Methods /Functions 

# Array Creation

## np.array()
Converts a list or tuple into a Numpy array.

In [8]:
import numpy as np

In [10]:
my_list = [1, 2, 3]
array = np.array(my_list)
print(array)

[1 2 3]


In [14]:
array = np.zeros((2, 3))
print(array)

[[0. 0. 0.]
 [0. 0. 0.]]


In [16]:
array = np.ones((2, 2))
print(array)

[[1. 1.]
 [1. 1.]]


In [18]:
array = np.empty((2, 3))
print(array)

[[0. 0. 0.]
 [0. 0. 0.]]


In [20]:
array = np.arange(0, 10, 2)
print(array)

[0 2 4 6 8]


In [22]:
a12 = np.arange(0,10)

In [24]:
a11 = np.arange(12).reshape(3,4)

In [26]:
a11

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [28]:
a33= np.arange(27).reshape(3,3,3)

In [30]:
a33


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [32]:
array = np.linspace(0, 1, 5)
print(array) 

[0.   0.25 0.5  0.75 1.  ]


In [34]:
array = np.linspace(0, 10,4 )
array

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [36]:
array = np.eye(3)
print(array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [38]:
array = np.full((2, 3), 7)
print(array)

[[7 7 7]
 [7 7 7]]


## Manipulation

In [41]:
a = np.arange(24)

In [43]:
A

NameError: name 'A' is not defined

In [45]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [47]:
a = np.arange(24).reshape(6,4)

In [49]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [51]:
import numpy as np

array = np.array([1, 2, 3, 4, 5, 6])
reshaped_array = np.reshape(array, (2, 3))
reshaped_array 

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
a21

NameError: name 'a21' is not defined

In [55]:
np.transpose(a21)

NameError: name 'a21' is not defined

In [57]:
array = np.array([[1, 2, 3], [4, 5, 6]])
transposed_array = np.transpose(array)
transposed_array

array([[1, 4],
       [2, 5],
       [3, 6]])

In [59]:
a22 = np.arange(12).reshape(3,4)

In [61]:
a22

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [63]:
a22.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [65]:
array = np.array([[1, 2], [3, 4]])

In [67]:
a21


NameError: name 'a21' is not defined

In [69]:
np.ravel(a21)

NameError: name 'a21' is not defined

In [71]:
a33


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [73]:
flattened_array = np.ravel(array)
flattened_array

array([1, 2, 3, 4])

In [75]:
a21 = np.array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [77]:
a22 = np.arange(12).reshape(3,4)

In [79]:
a22

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [81]:
a21


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [83]:
np.concatenate((a21,a22),axis= 0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [85]:
np.concatenate((a21,a22),axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [87]:
a = np.arange(12).reshape(6,2)

In [89]:
b = np.arange(12).reshape(2,6)

In [91]:
np.concatenate((a,b))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 6

In [93]:
def func(a,b,c):
    print(a)
func(10,20,30)
    

10


In [95]:
np.concatenate((a21,a22),axis = 1)   

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [97]:
np.concatenate((a21,a22),axis = 0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [99]:
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

np.concatenate((array1,array2),axis = 1) 

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [101]:
concatenated_array = np.concatenate((array1, array2), axis=0)   #axis = 0 for row wise concatenation
concatenated_array

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [103]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

In [105]:
a21


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [107]:
a22

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [109]:
np.vstack((a21,a22))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [111]:
vstacked_array = np.vstack((array1, array2))
vstacked_array 

array([[1, 2, 3],
       [4, 5, 6]])

In [113]:
np.hstack((a21,a22))

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [115]:
array1 = np.array([1, 2, 3])

array2 = np.array([4, 5, 6])

In [117]:
hstacked_array = np.hstack((array1, array2))
hstacked_array

array([1, 2, 3, 4, 5, 6])

In [119]:
array = np.array([1, 2, 3, 4, 5, 6])
split_array = np.split(array, 3)
split_array

[array([1, 2]), array([3, 4]), array([5, 6])]

In [121]:
a21


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [123]:
a11

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [125]:
np.mean(a21)

5.5

In [127]:
import numpy as np

array = np.array([1, 2, 3, 4, 5])
mean_value = np.mean(array)
mean_value

3.0

In [129]:
np.median(a11)

5.5

In [131]:
a = np.arange(9)

In [133]:
np.median(a)

4.0

In [135]:
median_value = np.median(array)
median_value 

3.0

In [137]:
std_deviation = np.std(array)
std_deviation

1.4142135623730951

In [139]:
np.std(a11)

3.452052529534663

In [141]:
variance_value = np.var(array)
variance_value

2.0

In [143]:
a21


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [145]:
a33

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [147]:
np.min(a21)

0

In [149]:
min_value = np.min(array)
min_value 

1

In [151]:
max_value = np.max(array)
max_value 

5

In [153]:
a21


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [155]:
np.sum(a21)

66

In [157]:
sum_value = np.sum(array)
sum_value 

15

In [159]:
np.prod(a21,axis = 0)

array([  0,  45, 120, 231])

In [161]:
np.prod(a21,axis = 1)

array([   0,  840, 7920])

In [163]:
array


array([1, 2, 3, 4, 5])

In [165]:
product_value = np.prod(array,axis =0 )
product_value 

120

In [167]:
import numpy as np

In [169]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [171]:
np.prod(a,axis = 0)  

array([  0,  45, 120, 231])

In [173]:
np.prod(a,axis = 1) 

array([   0,  840, 7920])

In [175]:
np.random.rand(50).reshape(5,10)

array([[0.28719521, 0.08168534, 0.26920897, 0.84116934, 0.28795316,
        0.55670656, 0.42502563, 0.16848901, 0.64777466, 0.14833685],
       [0.1025003 , 0.14702149, 0.46235127, 0.96978699, 0.07945067,
        0.57933381, 0.9105288 , 0.03287768, 0.90596532, 0.02005908],
       [0.66827508, 0.46163988, 0.68450632, 0.20311999, 0.04737228,
        0.78324373, 0.04033779, 0.34676159, 0.14338712, 0.62512809],
       [0.21668163, 0.96263205, 0.85199239, 0.23946127, 0.97939786,
        0.21415784, 0.43752217, 0.90897853, 0.28556894, 0.35448295],
       [0.53525588, 0.94980147, 0.03964669, 0.04566458, 0.95400272,
        0.42309068, 0.77097164, 0.30225691, 0.66749633, 0.21215638]])

In [177]:
import numpy as np
random_values = np.random.rand(3)
random_values

array([0.76888789, 0.78282398, 0.6056506 ])

In [179]:
random_normal = np.random.randn(3)
random_normal

array([ 0.50574007,  0.45316345, -0.45166602])

In [181]:
np.random.randint(1,10,5)

array([1, 4, 7, 5, 5])

In [183]:
random_integers = np.random.randint(1, 10, 3)
random_integers 

array([4, 5, 2])

In [185]:
a = np.arange(12)

In [187]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [189]:
np.random.choice(a,5)

array([ 4,  9,  4, 11,  2])

In [191]:
array = np.array([10, 20, 30, 40, 50])
random_choice = np.random.choice(array, 3)
random_choice 

array([40, 50, 50])

In [193]:

import numpy as np

In [195]:
sales_targets = np.zeros(5)
print("Sales Targets (Q1):", sales_targets)

Sales Targets (Q1): [0. 0. 0. 0. 0.]


In [197]:
game_grid = np.ones((5, 5))
print("Game Grid (Q2):\n", game_grid)

Game Grid (Q2):
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [199]:
data_points = np.linspace(0, 100, 10)
print("Data Points (Q3):", data_points)

Data Points (Q3): [  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


In [201]:

identity_matrix = np.eye(4)
print("Identity Matrix (Q4):\n", identity_matrix)

Identity Matrix (Q4):
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [209]:
array = np.array([1, 2, 3, 4, 5, 6])
reshaped_array = array.reshape(2, 3)
print("Reshaped Array (Q1):\n", reshaped_array)
# Output:

Reshaped Array (Q1):
 [[1 2 3]
 [4 5 6]]


In [205]:
combined_array = np.concatenate(([1, 2, 3], [4, 5, 6]))
split_arrays = np.split(combined_array, 2)
print("Combined Array (Q2):", combined_array)
print("Split Arrays (Q2):", split_arrays)

Combined Array (Q2): [1 2 3 4 5 6]
Split Arrays (Q2): [array([1, 2, 3]), array([4, 5, 6])]


In [207]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
flattened_matrix = matrix.ravel()
print("Flattened Matrix (Q3):", flattened_matrix)

Flattened Matrix (Q3): [1 2 3 4 5 6 7 8 9]


In [211]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
transposed_matrix = matrix.T
print("Transposed Matrix (Q4):\n", transposed_matrix)

Transposed Matrix (Q4):
 [[1 4]
 [2 5]
 [3 6]]


In [213]:
random_floats = np.random.rand(100)
print("Random Floats (Q1):", random_floats[:10]) 

Random Floats (Q1): [0.56160071 0.4949791  0.14685104 0.0727644  0.67953219 0.64238842
 0.95423393 0.3479939  0.07322321 0.42244842]


In [215]:
random_integers = np.random.randint(10, 50, size=(3, 3))
print("Random Integers (Q2):\n", random_integers)

Random Integers (Q2):
 [[17 44 26]
 [19 34 19]
 [12 49 15]]


In [217]:
sampled_array = np.random.choice([1, 2, 3, 4, 5, 6, 7, 8, 9], size=5, replace=False)
print("Sampled Array (Q3):", sampled_array)

Sampled Array (Q3): [2 4 5 1 7]


In [219]:
data = np.array([10, 20, 30, 40, 50])
mean = np.mean(data)
median = np.median(data)
std_dev = np.std(data)
print("Mean (Q1):", mean)        # Output: 30.0
print("Median (Q1):", median)    # Output: 30.0
print("Standard Deviation (Q1):", std_dev)

Mean (Q1): 30.0
Median (Q1): 30.0
Standard Deviation (Q1): 14.142135623730951


In [221]:
matrix = np.array([[1, 2], [3, 4], [5, 6]])
min_value = np.min(matrix)
max_value = np.max(matrix)
print("Min Value (Q2):", min_value)  # Output: 1
print("Max Value (Q2):", max_value)

Min Value (Q2): 1
Max Value (Q2): 6


In [227]:
percentiles = np.percentile([5, 10, 15, 20, 25, 30], [25, 50, 75])
print("Percentiles (Q3):", percentiles)


Percentiles (Q3): [11.25 17.5  23.75]


## indexing and slicing

In [230]:
a11


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [232]:
a11[0:3]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [234]:
import numpy as np

array = np.array([10, 20, 30, 40, 50])

In [236]:
first_element = array[0]

In [238]:
array[-1]

50

In [240]:
a21


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [242]:
a21[0:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [244]:
a21


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [246]:
a21[0:2,0:2 ]

array([[0, 1],
       [4, 5]])

In [248]:
a33 = np.arange(27).reshape(3,3,3)

In [250]:
a33


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [252]:
a33[1:,0:2,-1  ]

array([[11, 14],
       [20, 23]])

In [254]:
a21[1,0]

4

In [256]:
a21


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [258]:
a21[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [260]:
a21[0:2,2:]

array([[2, 3],
       [6, 7]])

In [262]:
a21[1,1]

5

In [264]:
a21[]

SyntaxError: invalid syntax (2915717979.py, line 1)

In [274]:
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [276]:
element = array_2d[1, 2] 

In [278]:
first_row = array_2d[0]

In [280]:
first_column = array_2d[:, 0]

In [282]:
import numpy as np
array = np.array([10, 20, 30, 40, 50])

slice_1 = array[1:4] 

### **Boolean Indexing in NumPy**

In [284]:
a11

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [289]:
a11>3

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [291]:
a11[mask]a11[a11>3 ]

array([ 4,  5,  6,  7,  8,  9, 10, 11])

In [293]:
mask = a11>3

In [295]:
a11[mask]

array([ 4,  5,  6,  7,  8,  9, 10, 11])

In [297]:
a11[mask]

array([ 4,  5,  6,  7,  8,  9, 10, 11])

In [299]:
a11

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [301]:
a11[a11>5]

array([ 6,  7,  8,  9, 10, 11])

In [303]:
a11[a11>=5]

array([ 5,  6,  7,  8,  9, 10, 11])

In [305]:
import numpy as np

array = np.array([10, 20, 30, 40, 50])

In [307]:
mask = array > 25 
filtered_array = array[mask]

In [309]:
array = np.array([10, 20, 30, 40, 50])

# Apply multiple conditions: elements greater than 15 and less than 45
mask = (array > 15) & (array < 45)

# Filter the original array using the combined condition
filtered_array = array[mask]

In [311]:
import numpy as np

In [313]:
a21 = np.array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [315]:
(a21>=5)

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [317]:
(a21<=9)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False]])

In [319]:
mask =(a21<=9) & (a21>=5)

In [321]:
a21[mask]

array([5, 6, 7, 8, 9])

In [323]:
mask = (a21>=5) & (a21<=9)

In [325]:
a21[mask]

array([5, 6, 7, 8, 9])

In [327]:
a11 = np.arange(2,12)

In [329]:
a11

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [331]:
np.where(a11>6)

(array([5, 6, 7, 8, 9], dtype=int64),)

In [333]:
a21


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [335]:
a21 = np.arange(12).reshape(3,4)

In [337]:
np.where(a21>5)

(array([1, 1, 2, 2, 2, 2], dtype=int64),
 array([2, 3, 0, 1, 2, 3], dtype=int64))

In [339]:
a55 = np.array([5,87,99,66,88,55,44])

In [341]:
np.where(a55>66)

(array([1, 2, 4], dtype=int64),)

In [343]:
array = np.array([10, 20, 30, 40, 50])

In [345]:
indices = np.where(array > 30)

In [347]:
filtered_array = array[indices]  

In [349]:
array = np.array([10, 20, 30, 40, 50])
array

array([10, 20, 30, 40, 50])

In [351]:
np.where(array > 30)

(array([3, 4], dtype=int64),)

In [353]:
names = np.array(['Alice', 'Bob', 'Charlie', 'David', 'Eve',"Ajau"])

# Create a boolean mask for names that start with the letter 'A'
mask = np.char.startswith(names, 'A')

In [355]:
names[mask] 

array(['Alice', 'Ajau'], dtype='<U7')

In [357]:
names = np.array(['Alice', 'Bob', 'Charlie', 'David', 'Eve',"Ajau"])

In [359]:
names

array(['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Ajau'], dtype='<U7')

In [361]:
np.char.startswith(names,"A")

array([ True, False, False, False, False,  True])

In [363]:
names[np.char.startswith(names,"A")]

array(['Alice', 'Ajau'], dtype='<U7')

In [365]:
a = "hello world"

In [367]:
a.startswith("a")

False

In [371]:
# Replace all elements greater than 30 with the value 99
array = np.array([10, 20, 30, 40, 50])


array[array > 30] = 99 

In [373]:
array

array([10, 20, 30, 99, 99])

In [375]:
a11

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [377]:
a11> 4

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [379]:
a11[a11>4] = 8

In [381]:
a11

array([2, 3, 4, 8, 8, 8, 8, 8, 8, 8])

In [383]:
l = [1,2,3]

In [385]:
l[0]

1

In [387]:
a11


array([2, 3, 4, 8, 8, 8, 8, 8, 8, 8])

In [389]:
a11[a11>5]

array([8, 8, 8, 8, 8, 8, 8])

## fancy indexing

In [392]:
import numpy as np

array = np.array([10, 20, 30, 40, 50])

In [394]:
fancy_indexed = array[[1, 3, 4]] 

In [396]:
fancy_indexed


array([20, 40, 50])

In [398]:
a55

array([ 5, 87, 99, 66, 88, 55, 44])

In [400]:
a55[[1,3,6]]

array([87, 66, 44])

In [402]:
fancy_indexed_neg = array[[-1, -3]]

In [404]:
array_2d = np.array([[10, 20, 30],
                     [40, 50, 60],
                     [70, 80, 90]])

In [406]:
array_2d[1,0:]

array([40, 50, 60])

In [408]:
array_2d[[0, 1, 2],[1, 0, 2]]

array([20, 40, 90])

In [410]:
array_2d[[0,1,2],[0,1,2]]

array([10, 50, 90])

In [412]:
array_2d[[0, 1, 2], [1, 0, 2]]

array([20, 40, 90])

In [414]:
rows = array_2d[[0, 2]]
columns = array_2d[:, [1, 2]]

### **3. Fancy Indexing with Repetition**

In [417]:
array = np.array([100, 200, 300, 400, 500])

In [419]:
array

array([100, 200, 300, 400, 500])

In [421]:
array[[0,4,0,4]]

array([100, 500, 100, 500])

In [423]:
array[[0, 4, 0, 4]] 

array([100, 500, 100, 500])

### **4. Fancy Indexing with Boolean Arrays**

In [426]:
array = np.array([5, 10, 15, 20, 25, 30])

In [428]:
mask = array > 15

In [430]:

fancy_indexed = array[mask]

### **5. Fancy Indexing vs Basic Slicing**

In [433]:
array = np.array([10, 20, 30, 40, 50])

slice_result = array[1:4] 
fancy_indexed = array[[0, 2, 4]] 

In [435]:
a11

array([2, 3, 4, 8, 8, 8, 8, 8, 8, 8])

In [437]:
for i in a11:
    print(i)

2
3
4
8
8
8
8
8
8
8


In [439]:
a21

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [441]:
a21 = [ [0,1,2,3],[4,5,6,7],[8,9,10,11]]

In [443]:
for i in a21:
    print(i)

[0, 1, 2, 3]
[4, 5, 6, 7]
[8, 9, 10, 11]


In [445]:
a33

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [447]:
for i in a33:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [449]:
a11

for i in a11:
    print(i)

2
3
4
8
8
8
8
8
8
8


In [451]:
a22

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [453]:
for i in a22:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [455]:
a33

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [457]:
for i in a33:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [459]:
for i in np.nditer(a33):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


###### Stacking


###### anu

In [468]:
# horizontal stacking
a44 = np.arange(12).reshape(3,4)
a55 = np.arange(12,24).reshape(3,4)

In [470]:
# horizontal stacking
a66 = np.arange(12).reshape(4,3)
a77 = np.arange(12,24).reshape(3,4)

In [474]:
a44


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [476]:
a55

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [478]:
np.hstack((a44,a55))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [480]:
np.hstack((a44,a55))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [482]:
# Vertical stacking
np.vstack((a44,a55))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [484]:
np.vstack((a44,a55))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [486]:
a44

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [488]:
a55


array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting

In [491]:
import numpy as np

array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8]])

In [493]:
splits = np.hsplit(array, 2)

print(splits)

[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]


In [495]:
array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [497]:
np.hsplit(array,4)

[array([[1],
        [5]]),
 array([[2],
        [6]]),
 array([[3],
        [7]]),
 array([[4],
        [8]])]

In [499]:
import numpy as np

array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

splits = np.vsplit(array, 3)

print(splits)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [503]:
import numpy as np

array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

In [505]:
splits = np.vsplit(array, 3)

print(splits)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


# Array Mutability

In [510]:
 import numpy as np
arr = np.array([1, 2, 3, 4, 5])
arr[2] = 99

In [512]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
arr[1:4] = 0

In [514]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
mask = arr > 2
arr[mask] = 99 

In [516]:
arr


array([ 1,  2, 99, 99, 99])

In [518]:
arr> 80

array([False, False,  True,  True,  True])

In [520]:
arr[arr>80] =0

In [522]:
arr

array([1, 2, 0, 0, 0])