##  Filtering Arrays in NumPy

###  What is Boolean Indexing?
Boolean indexing means using a boolean array (an array of `True`/`False` values)




In [3]:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

In [5]:

mask = arr > 3

In [7]:

filtered = arr[mask]

In [9]:

print("Filtered elements (greater than 3):", filtered)

Filtered elements (greater than 3): [4 5 6]


In [11]:
# Apply the mask to filter the array
filtered = arr[mask]

print("Filtered elements (greater than 3):", filtered)

Filtered elements (greater than 3): [4 5 6]


You can combine multiple conditions using:

* `&` (logical AND)
* `|` (logical OR)
* `~` (logical NOT)

In [14]:
arr = np.array([1, 2, 3, 4, 5, 6])

In [16]:
(arr > 2) & (arr < 6)

array([False, False,  True,  True,  True, False])

In [18]:

arr[(arr > 2) & (arr < 6)]

array([3, 4, 5])

In [20]:
arr[(arr <= 3) | (arr > 5)]

array([1, 2, 3, 6])

In [22]:
# Elements less than or equal to 3 OR greater than 5


arr[(arr <= 3) | (arr > 5)]

array([1, 2, 3, 6])

###  Filtering 2D Arrays

In [25]:
matrix = np.array([
    [10, 15, 20],
    [25, 30, 35]
])

# Get elements greater than 20
print("Values > 20:", matrix[matrix > 20])

Values > 20: [25 30 35]


In [27]:
scores = np.array([85, 92, 78, 88, 95, 72, 89, 94, 68, 90])

In [29]:
# Find students who scored more than 90
high_scores = scores[scores > 90]

In [31]:
print("Students scoring > 90:", high_scores)

Students scoring > 90: [92 95 94]


In [33]:
np.random.randint(0,15)

14

In [35]:
prices = np.array([250, 499, 520, 310, 800, 999, 450, 720])

In [37]:
prices[prices%2==0]

array([250, 520, 310, 800, 450, 720])

In [39]:
prices[prices>500]

array([520, 800, 999, 720])